export const bitacoraConstants = {
    BITACORA_GETALL : 'BITACORA_GETALL',
    BITACORA_GETALL_SET : 'BITACORA_GETALL_SET',
    BITACORA_PAGINATION_REQUEST: 'BITACORA_PAGINATION_REQUEST',
    BITACORA_PAGINATION_SUCCESS: 'BITACORA_PAGINATION_SUCCESS',
    PAGINATION_SET: 'PAGINATION_SET',
    BITACORA_CLEAR_SET: 'BITACORA_CLEAR_SET'
};
