export const providerConstants = {
    REGISTER_REQUEST: 'PROVIDERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'PROVIDERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'PROVIDERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'PROVIDERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'PROVIDERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'PROVIDERS_LOGIN_FAILURE',

    LOGOUT: 'PROVIDERS_LOGOUT',

    PROVIDERS_GETALL : 'PROVIDERS_GETALL',
    PROVIDERS_GETALL_SET : 'PROVIDERS_GETALL_SET',
    PROVIDERS_GETALL_ENABLED : 'PROVIDERS_GETALL_ENABLED',
    PROVIDERS_GETALL_ENABLED_SET : 'PROVIDERS_GETALL_ENABLED_SET',
    PROVIDERS_PAGINATION_REQUEST: 'PROVIDERS_PAGINATION_REQUEST',
    PROVIDERS_PAGINATION_SUCCESS: 'PROVIDERS_PAGINATION_SUCCESS',
    PAGINATION_SET: 'PAGINATION_SET',
    PROVIDER_TEMPORAL_REQUEST:'PROVIDER_TEMPORAL_REQUEST',
    GETALL_FAILURE: 'PROVIDERS_GETALL_FAILURE',

    DELETE_REQUEST: 'PROVIDERS_DELETE_REQUEST',
    DELETE_OPERATION: 'DELETE_OPERATION',
    DELETE_SUCCESS: 'PROVIDERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'PROVIDERS_DELETE_FAILURE'
};
