export const S2Constants = {
   REQUEST_CREATION_S2:'REQUEST_CREATION_S2',
   REQUEST_LIST_S2: 'REQUEST_LIST_S2',
   SET_LIST_S2: 'SET_LIST_S2',
   PAGINATION_SET_SCHEMA2: 'PAGINATION_SET_SCHEMA2',
   DELETE_REQUESTS2: 'DELETE_REQUESTS2',
   DELETE_OPERATIONS2: 'DELETE_OPERATIONS2',
   FILL_REG_S2_EDIT: 'FILL_REG_S2_EDIT',
   UPDATE_REG_S2: 'UPDATE_REG_S2',
   SET_CLEAR_S2:'SET_CLEAR_S2',
   /* v2 */
   REQUEST_CREATION_S2v2:'REQUEST_CREATION_S2v2',
}
