export const S3PConstants = {
    REQUEST_CREATION_S3P:'REQUEST_CREATION_S3P',
    REQUEST_LIST_S3P: 'REQUEST_LIST_S3P',
    SET_LIST_S3P: 'SET_LIST_S3P',
    PAGINATION_SET_SCHEMAS3P: 'PAGINATION_SET_SCHEMAS3P',
    DELETE_REQUESTS3P: 'DELETE_REQUESTS3P',
    DELETE_OPERATIONS3P: 'DELETE_OPERATIONS3P',
    FILL_REG_S3P_EDIT: 'FILL_REG_S3P_EDIT',
    UPDATE_REG_S3P: 'UPDATE_REG_S3P',
    SET_CLEAR_S3P:'SET_CLEAR_S3P'
}
