export const S3SConstants = {
    REQUEST_CREATION_S3S:'REQUEST_CREATION_S3S',
    REQUEST_LIST_S3S: 'REQUEST_LIST_S3S',
    SET_LIST_S3S: 'SET_LIST_S3S',
    PAGINATION_SET_SCHEMA3S: 'PAGINATION_SET_SCHEMA3S',
    DELETE_REQUESTS3S: 'DELETE_REQUESTS3S',
    DELETE_OPERATIONS3S: 'DELETE_OPERATIONS3S',
    FILL_REG_S3S_EDIT: 'FILL_REG_S3S_EDIT',
    UPDATE_REG_S3S: 'UPDATE_REG_S3S',
    SET_CLEAR_S3S:'SET_CLEAR_S3S'
}
