version: "3"

services:
  app:
    build:
      context: ./
    volumes:
    #  - ./extensions:/directus/extensions  # Asegúrate de que ./extensions/hooks/ existe y tenga tus hooks
      - ./migrations:/directus/migrations
      - ./templates:/directus/templates
    command: >
      sh -c "node cli.js bootstrap &&
         node cli.js schema apply --yes /directus/migrations/colecciones.yaml &&
         sh /directus/init-modificaciones-db.sh &&
         npx directus start"

    restart: always
    ports:
      - 8055:8055
    depends_on:
      - db
    environment:
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: "directus"
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: {}
