version: "3"
services:

  app:
    build: 
      context: ./
    volumes:
      - ./extensions:/directus/extensions
      - ./migrations:/directus/migrations
      - ./templates:/directus/templates
    command: >
        sh -c "node cli.js bootstrap &&
              node cli.js schema apply --yes /directus/migrations/colecciones.yaml &&
              pm2-runtime start ecosystem.config.cjs"
    restart: always
    ports:
      - 8055:8055
    depends_on:
      - db
    environment:
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      PUBLIC_URL: ${PUBLIC_URL}
      DB_CLIENT: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_VERSION: "14"
      WEBSOCKETS_ENABLED: 0
      TELEMETRY: 0
      GRAPHQL_INTROSPECTION: 0
      CACHE_ENABLED: 0
      WEBSOCKETS_GRAPHQL_ENABLED: 0
      CORS_CREDENTIALS: 1
      CORS_ENABLED: 1
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
      EMAIL_SMTP_HOST: ${SMTP_HOST}
      EMAIL_SMTP_PORT: ${SMTP_PORT}
      EMAIL_SMTP_USER: ${SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${SMTP_PASSWORD}

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: "directus"
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    #ports:
      #- 5432:5432
      
volumes:
  postgres: {}
